name: Build and Upload DLLs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.25.0'

    - name: Install Dependencies
      run: |
        choco install ninja --confirm

    - name: Configure Build
      run: |
        mkdir build
        cd build
        cmake -G "Ninja" ..

    - name: Build Project
      run: |
        cd build
        cmake --build . --config Release

    - name: Upload DLLs
      uses: actions/upload-artifact@v3
      with:
        name: DLLs
        path: |
          build/*.dll
