name: Build and Upload DLLs

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Initialize submodules
      run: git submodule update --init --recursive


    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.25.0'

    - name: Install Dependencies
      run: |
        choco install ninja --confirm

    - name: Configure Build
      run: cmake -S . -B build ./build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

    - name: Build Project
      run: cmake --build ./build --config Release --target uevr

    - name: Upload DLLs
      uses: actions/upload-artifact@v3
      with:
        name: DLLs
        path: |
          build/*.dll
